name: Apptainer Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Makefile'
      - 'container.def'
      - 'install.jl'
      - 'Project.toml'
      - 'scripts/*'
      - 'src/*'
      - '.github/workflows/apptainer-image.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Singularity
      uses: eWaterCycle/setup-apptainer@v2
      with:
       apptainer-version: 1.2.2
    - name: Build apptainer image
      run: apptainer build --fakeroot spatialrust-v1.sif container.def
    - name: Execute the single run parameterization
      run: apptainer run --bind ./:/srv/results spatialrust-v1.sif scripts/OneRun.jl
