name: Docker Image / Makefile CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'Makefile'
      - 'install.jl'
      - 'Project.toml'
      - 'scripts/*'
      - 'src/*'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make build
    - name: Execute the single run parameterization
      run: docker run --rm comses/spatialrust julia scripts/OneRun.jl
