name: Singularity Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Singularity.def'
      - 'install.jl'
      - 'Project.toml'
      - 'scripts/*'
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Singularity
      uses: eWaterCycle/setup-singularity@v7
      with:
       singularity-version: 3.8.3
    - name: Build Singularity image
      run: singularity build --fakeroot spatialrust-v1 Singularity.def
    - name: Execute the single run parameterization
      run: singularity run --bind ./results:/code/results --pwd /code spatialrust-v1 scripts/OneRun.jl

   
