name: Singularity Image CI

on:
  push:
    branches: [ env-vars ]
    paths:
      - 'Sing2.def'
      - 'install.jl'
      - 'Project.jl'
      - 'scripts/*'
  pull_request:
    branches: [ env-vars ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Singularity
     uses: eWaterCycle/setup-singularity@v7
     with:
       singularity-version: 3.8.3
    - run: |
      ls -a $GITHUB_WORKSPACE
      ls -a /opt
#    - uses: actions/cache@v3
#      id: singularity
#      with:
#        path: /opt/hostedtoolcache/singularity/
#        key: singk
#    - name: Setup Singularity
#      if: steps.singularity.outputs.cache-hit != 'true'
#      uses: eWaterCycle/setup-singularity@v7
#      with:
#        singularity-version: 3.8.3
#    - uses: actions/cache@v3
#      id: image
#      with:
#        path: $GITHUB_WORKSPACE/.singularity/cache
#        key: imagek
#    - name: Build Singularity image
#      if: steps.image.outputs.cache-hit != 'true'
#      run: singularity build --fakeroot spatialrust-v1 Sing2.def
#    - name: Execute the single run parameterization
#      run: singularity run spatialrust-v1 scripts/OneRun.jl
