name: Singularity Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Singularity
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Build Singularity image
      run: singularity build --fakeroot spatialrust-v1 Sing2.def
    - name: Execute the single run parameterization
      run: singularity run spatialrust-v1 julia scripts/OneRun.jl